### ISSUE TITLE
Mac configure: error: Please reinstall the OpenSSL library

### ISSUE THREAD

**Issue by lilianjin** [cdoco/php-jwt#24]
openssl version  
OpenSSL 1.0.2q  20 Nov 2018

**Comment by lilianjin** [comment]
checking whether to enable jwt support... yes, shared
checking whether to use OpenSSL library... yes, shared
checking for OpenSSL library in default path... OpenSSL library not found

**Comment by lilianjin** [comment]
Thank, Has been solved!

**Comment by pableiros** [comment]
I still having the same issue even with the `--with-openssl=/usr/bin/openssl` using a `M1 Pro`
